### PR TITLE
#218 Fix issue that caused changing password in settings to not stick

### PR DESCRIPTION
**Pull request by cmho**

### CODE REVIEW

**Comment by sublimemarch** [comment]
:ship:

**Comment by sublimemarch** [comment]
Why did this get closed instead of being merged in?

**Comment by carlydotwebsite** [comment]
it's been merged in now; I was merging things to an integration branch and
then merging that in to decrease the # of deploys

**Comment by sublimemarch** [comment]
Awesome, super cool

**Pull request closed without merging**
